<?php

namespace Vivait\WidgetBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WidgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WidgetRepository extends EntityRepository
{
	/**
	 * @param $position
	 * @return Widget[]
	 */
	public function getWidgetByPosition($position) {
		$query = $this->createQueryBuilder('w')
			->where('w.position = :position')
			->orderBy('w.priority')
			->getQuery();

		$widgets = $query
			->setParameter('position', $position)
			->getResult();

		return $widgets;
	}
}
